/** Every user command of the editor (canon C3/C11): menus, shortcuts and the command palette dispatch these. */
export enum Action {
  New = 'new',
  Open = 'open',
  Save = 'save',
  ExportImage = 'export-image',
  ExportMovie = 'export-movie',
  SurpriseScene = 'surprise-scene',
  CopyImage = 'copy-image',
  ShareLink = 'share-link',
  DocumentSetup = 'document-setup',
  LoadDemo = 'load-demo',
  Undo = 'undo',
  Redo = 'redo',
  Cut = 'cut',
  Copy = 'copy',
  Paste = 'paste',
  Duplicate = 'duplicate',
  Replicate = 'replicate',
  Delete = 'delete',
  SelectAll = 'select-all',
  SelectNone = 'select-none',
  CopyMaterial = 'copy-material',
  PasteMaterial = 'paste-material',
  Group = 'group',
  Ungroup = 'ungroup',
  Land = 'land',
  Attributes = 'attributes',
  EditMaterial = 'edit-material',
  EditObject = 'edit-object',
  ObjectLibrary = 'object-library',
  Randomize = 'randomize',
  HideSelected = 'hide-selected',
  ShowAll = 'show-all',
  FrameSelected = 'frame-selected',
  FrameAll = 'frame-all',
  ViewCamera = 'view-camera',
  ViewDirector = 'view-director',
  ViewTop = 'view-top',
  ViewFront = 'view-front',
  ViewSide = 'view-side',
  QuadView = 'quad-view',
  ToggleSidePanel = 'toggle-side-panel',
  ToggleDepthCue = 'toggle-depth-cue',
  ToggleGrid = 'toggle-grid',
  ToggleGizmo = 'toggle-gizmo',
  ToggleSnap = 'toggle-snap',
  ResetCamera = 'reset-camera',
  PickFocus = 'pick-focus',
  CameraFromView = 'camera-from-view',
  ZoomIn = 'zoom-in',
  ZoomOut = 'zoom-out',
  Render = 'render',
  StopRender = 'stop-render',
  ClearRender = 'clear-render',
  ToggleLiveRender = 'toggle-live-render',
  TakeSnapshot = 'take-snapshot',
  CompareSnapshot = 'compare-snapshot',
  TabCreate = 'tab-create',
  TabEdit = 'tab-edit',
  TabSky = 'tab-sky',
  SkyLibrary = 'sky-library',
  MaterialLibrary = 'material-library',
  CommandPalette = 'command-palette',
  Shortcuts = 'shortcuts',
  About = 'about',
  InstallApp = 'install-app',
  Bookmark = 'bookmark',
  SaveBookmark = 'save-bookmark',
}

/** Actions that take a numeric argument (bookmark slots). */
export interface ActionCall {
  readonly action: Action;
  readonly arg?: number;
}
